---
title: "Reading Delimited Data"
format: html
toc: TRUE
editor_options: 
  chunk_output_type: inline
---

## Task 2 Reading Delimited Data

```{r}
# Load in the tidyverse
library(tidyverse)
```

### Glass Data

```{r}
data_connection <- "https://www4.stat.ncsu.edu/online/datasets/glass.data"
columns <- c("Id", "RI", "Na", "Mg", "Al", "Si", 
             "K", "Ca", "Ba", "Fe", "Glass_Type")
glass_data <- read_csv(data_connection,
                       col_names = columns)

glass_data
```

```{r}
# Make a function to perform the conversion, for ease of viewing the code
# If the Glass_Type isn't 1-7, then unknown, just in case they add a new type
glass_type_convert <- function(col) {
  ifelse(col == 1, "building_windows_float_processed",
         ifelse(col == 2, "building_windows_non_float_processed",
                ifelse(col == 3, "vehicle_windows_float_processed",
                      ifelse(col == 4, "vehicle_windows_non_float_processed",
                             ifelse(col == 5, "containers",
                                    ifelse(col == 6, "tableware",
                                           ifelse(col == 7, "headlamps",
                                                  "unknown")))))))
}

# Convert Glass_Type variable from numbers to character strings, then filter
glass_data_filtered <- glass_data |>
  mutate(Glass_Type = as.factor(glass_type_convert(Glass_Type))) |>
  filter(Fe < 0.2, Glass_Type %in% c("tableware", "headlamps"))

glass_data_filtered
```
